import React from 'react';
import { Calendar, RefreshCw, Clock, ArrowRight, Sparkles } from 'lucide-react';
import PageHeader from '../components/common/PageHeader.jsx';
import Card, { CardHeader, CardTitle, CardContent } from '../components/common/Card.jsx';
import Badge from '../components/common/Badge.jsx';
import Button from '../components/common/Button.jsx';

export const Planner = () => {
  return (
    <div>
      <PageHeader
        title="Study Planner"
        subtitle="Daily timeline and weekly calendar generated by the deterministic priority engine."
        badge={<Badge variant="primary">Phase 1 Preview</Badge>}
        action={
          <Button icon={RefreshCw} variant="outline" size="sm">
            Regenerate Schedule
          </Button>
        }
      />

      <div className="space-y-6">
        {/* Timeline View Placeholder */}
        <Card>
          <CardHeader className="flex flex-row items-center justify-between">
            <div className="flex items-center gap-2">
              <Calendar className="w-5 h-5 text-indigo-600" />
              <CardTitle>Today's Time Slots (Capacity: 3.5 Hours)</CardTitle>
            </div>
            <span className="text-xs text-slate-500">Sorted by Priority Index</span>
          </CardHeader>
          <CardContent className="space-y-4">
            {/* Slot 1 */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between p-4 rounded-xl border border-slate-200 bg-slate-50/50 gap-3">
              <div className="flex items-start sm:items-center gap-3">
                <div className="px-2.5 py-1.5 rounded-lg bg-indigo-100 text-indigo-800 text-xs font-bold shrink-0">
                  09:00 - 10:15
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <h4 className="text-sm font-semibold text-slate-900">Database Management Systems</h4>
                    <Badge variant="primary" size="sm">Priority: 88.5</Badge>
                  </div>
                  <p className="text-xs text-slate-500 mt-0.5">Topic: BCNF & Lossless Decomposition (75 mins)</p>
                  <p className="text-[11px] text-slate-400 mt-0.5">Reason: Exam in 12 days + High topic difficulty</p>
                </div>
              </div>
              <div className="flex items-center gap-2 shrink-0">
                <Badge variant="neutral" size="sm">Pending</Badge>
                <Button size="sm">Start</Button>
              </div>
            </div>

            {/* Rest Interval */}
            <div className="flex items-center justify-center gap-2 py-1 text-slate-400 text-xs font-medium">
              <Clock className="w-3.5 h-3.5" />
              <span>15-Minute Pomodoro Rest Interval</span>
            </div>

            {/* Slot 2 */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between p-4 rounded-xl border border-slate-200 bg-slate-50/50 gap-3">
              <div className="flex items-start sm:items-center gap-3">
                <div className="px-2.5 py-1.5 rounded-lg bg-indigo-100 text-indigo-800 text-xs font-bold shrink-0">
                  10:30 - 11:30
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <h4 className="text-sm font-semibold text-slate-900">Operating Systems</h4>
                    <Badge variant="warning" size="sm">Priority: 74.0</Badge>
                  </div>
                  <p className="text-xs text-slate-500 mt-0.5">Topic: Virtual Memory & Page Replacement (60 mins)</p>
                  <p className="text-[11px] text-slate-400 mt-0.5">Reason: Unstudied syllabus deficit</p>
                </div>
              </div>
              <div className="flex items-center gap-2 shrink-0">
                <Badge variant="neutral" size="sm">Pending</Badge>
                <Button size="sm">Start</Button>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Adaptive Engine Notice Banner */}
        <div className="p-4 rounded-xl bg-purple-50/70 border border-purple-200/80 flex items-start gap-3">
          <Sparkles className="w-5 h-5 text-purple-600 shrink-0 mt-0.5" />
          <div className="text-xs text-purple-900">
            <p className="font-semibold">Adaptive Rescheduling Preview (Phase 8)</p>
            <p className="text-purple-700 mt-0.5 leading-relaxed">
              If a study slot is missed or interrupted, the Adaptive Engine will automatically calculate carryover duration and reschedule into the next open slot without manual student intervention.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Planner;
